#!/usr/bin/env node
/*
 * Regenerates the steady-state starting point 'm1-lab-glucose' (engine spec
 * §11.1). A cold-start cell with seed 0 in the default medium runs for 120,000
 * ticks (≈33 h, about 20 generations); its canonical state bytes are stored as
 * base64 together with their hash, in two places with the same content:
 *   src/engine/btc-presets.js        what the engine loads (data only)
 *   presets/m1-lab-glucose.json      the same snapshot as plain JSON
 *
 *   node tools/make-presets.js          write both files
 *   node tools/make-presets.js --check  exit 1 if either is stale (test d-7)
 */
'use strict';
const fs = require('fs');
const path = require('path');

const ENGINE = path.join(__dirname, '..', 'src', 'engine');
const OUT = path.join(ENGINE, 'btc-presets.js');
const OUT_JSON = path.join(__dirname, '..', 'presets', 'm1-lab-glucose.json');
const SPEC = { id: 'm1-lab-glucose', strain: 'm1-lab', seed: 0, ticks: 120000 };

function makePreset() {
  const M = require(path.join(ENGINE, 'btc-math.js'));
  const { Cell, ENGINE_VERSION } = require(path.join(ENGINE, 'btc-cell.js'));
  const cell = new Cell({ seed: SPEC.seed, strain: SPEC.strain, start: 'cold' });
  cell.advance(SPEC.ticks);
  const bytes = cell.stateBytes(false);
  return {
    strain: SPEC.strain, seed: SPEC.seed, ticks: SPEC.ticks, engineVersion: ENGINE_VERSION,
    hash: M.hash64(bytes), state: M.base64Encode(bytes),
  };
}

function render(preset) {
  const chunks = [];
  for (let i = 0; i < preset.state.length; i += 96) chunks.push("      '" + preset.state.slice(i, i + 96) + "'");
  return `// @deps
/*
 * Be the Cell: steady-state starting points (data only). GENERATED by
 * tools/make-presets.js from a cold start (seed ${preset.seed}, ${preset.ticks} ticks); do not edit.
 */
(function (root, factory) {
  if (typeof module === 'object' && module.exports) {
    module.exports = factory();
  } else {
    var B = root.BTC || (root.BTC = {});
    B.presets = factory();
  }
})(typeof self !== 'undefined' ? self : this, function () {
  'use strict';
  return {
    '${SPEC.id}': {
      strain: '${preset.strain}', seed: ${preset.seed}, ticks: ${preset.ticks}, engineVersion: '${preset.engineVersion}',
      hash: '${preset.hash}',
      state: [
${chunks.join(',\n')},
      ].join(''),
    },
  };
});
`;
}

function renderJSON(preset) {
  return JSON.stringify(Object.assign({ id: SPEC.id }, preset), null, 2) + '\n';
}

/** True when both stored copies hold exactly this preset. */
function isFresh(preset) {
  const stored = require(OUT)[SPEC.id];
  const json = fs.existsSync(OUT_JSON) ? fs.readFileSync(OUT_JSON, 'utf8') : '';
  return !!stored && stored.hash === preset.hash && stored.state === preset.state && json === renderJSON(preset);
}

if (require.main === module) {
  const preset = makePreset();
  if (process.argv.includes('--check')) {
    const fresh = isFresh(preset);
    const stored = require(OUT)[SPEC.id];
    console.log(fresh ? 'preset is fresh: ' + preset.hash : 'preset is STALE: stored ' + (stored && stored.hash) + ', fresh ' + preset.hash);
    process.exit(fresh ? 0 : 1);
  }
  fs.writeFileSync(OUT, render(preset));
  fs.mkdirSync(path.dirname(OUT_JSON), { recursive: true });
  fs.writeFileSync(OUT_JSON, renderJSON(preset));
  console.log('wrote ' + path.relative(process.cwd(), OUT) + ' and ' + path.relative(process.cwd(), OUT_JSON) + ' (' + preset.hash + ')');
}

module.exports = { makePreset, render, renderJSON, isFresh, SPEC };
